name: Generate Arcade Contribution Graphs

on:
  schedule:
    - cron: "0 */24 * * *" # Runs automatically every 24 hours
  workflow_dispatch: # Allows you to run it manually from the Actions tab
  push:
    branches:
      - main # Or your default branch name (e.g., master)

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Generate Contribution Graph SVGs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ shashwat12jha }}
